#!/usr/bin/env bash

case $1 in
    migrate)
        php artisan migrate:fresh
        php artisan db:seed
        ;;
    up)
        docker-compose up -d
        ;;
    down)
        docker-compose down
        ;;

esac
