version: "3.7"
 
networks:
  default:
    driver: bridge
 
services:
 
  app:
    build:
        context: .
        dockerfile: Dockerfile
    image: "php:7.4-apache"
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
        SERVICE_NAME: app
        SERVICE_TAGS: dev
    working_dir: /var/www/html/
    volumes:
        - ./:/var/www/html/
        - ./DockerFiles/Apache/:/etc/apache2/sites-enabled/
    ports:
        - 80:80
    networks:
        - default
 
  db:
    image: mysql:5.7.32
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - default
 
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8088:80"
    
volumes:
    dbdata:
        driver: local