version: '3.3'
networks:
  laravel: null
volumes:
  mysql: null
###########################################################################################
services:
  nginx:
    image: 'nginx:latest'
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - './:/var/www/html'
      - './build/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - php
      - mysql
    networks:
      - laravel
  ###########################################################################################
  mysql:
    image: 'mysql:latest'
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: Main
      MYSQL_USER: user
      MYSQL_PASSWORD: fcuk
      MYSQL_ROOT_PASSWORD: fcuk
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - 'mysql:/var/lib/mysql'
    networks:
      - laravel
  ###########################################################################################
  php:
    build:
      context: .
      dockerfile: ./build/docker/php/Dockerfile
    container_name: php
    volumes:
      - './:/var/www/html'
    links:
      - mysql
    ports:
      - '9000:9000'
    networks:
      - laravel
###########################################################################################
